### ISSUE TITLE
npm start throws an error

### ISSUE THREAD

**Issue by HadManySons** [AF-Tools/bullet-buddy#2]
From PowerShell:

```PS H:\Users\[redacted]\Desktop\bullet-buddy> npm start

> bullet-buddy@0.1.0 start H:\Users\[redacted]\Desktop\bullet-buddy
> react-scripts start`

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bullet-buddy@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bullet-buddy@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[redacted]\AppData\Roaming\npm-cache\_logs\2021-02-02T04_04_20_121Z-debug.log`

```

From the log file:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'G:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'G:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle bullet-buddy@0.1.0~prestart: bullet-buddy@0.1.0
6 info lifecycle bullet-buddy@0.1.0~start: bullet-buddy@0.1.0
7 verbose lifecycle bullet-buddy@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle bullet-buddy@0.1.0~start: PATH: A lot to redact in here, just operate on the assumption that my path was good.
9 verbose lifecycle bullet-buddy@0.1.0~start: CWD: H:\Users\[redacted]\Desktop\bullet-buddy
10 silly lifecycle bullet-buddy@0.1.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 silly lifecycle bullet-buddy@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle bullet-buddy@0.1.0~start: Failed to exec start script
13 verbose stack Error: bullet-buddy@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (G:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (G:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid bullet-buddy@0.1.0
15 verbose cwd H:\Users\[redacted]\Desktop\bullet-buddy
16 verbose Windows_NT 10.0.19042
17 verbose argv "G:\\Program Files\\nodejs\\node.exe" "G:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error bullet-buddy@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the bullet-buddy@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Sorry I don't have more to offer, not super savvy with JS or Node

**Comment by NicholasSchweikart** [comment]
Hello, sorry I dont check this often and just saw this issue. Did you run npm install first?
